- hosts: relays
  become: yes
  roles:
      - relays-setup
      - relays

- hosts: edges
  become: yes
  roles:
      - edges-setup
      - edges

- hosts: local
  become: yes
  roles:
      - v2ray
      - local-setup
      - local
