- name: Create /etc/neo/
  file: path=/etc/neo state=directory mode=0755

- name: Deploy config files
  template: src={{ item.src }} dest={{ item.dest }}
  loop:
      - { src: 'iptables.rules.v4.j2', dest: '/etc/neo/iptables.rules.v4' }
      - { src: 'iptables.rules.inner.v4.j2', dest: '/etc/neo/iptables.inner.rules.v4' }
      - { src: 'v2ray.config.json.j2', dest: '/etc/neo/v2ray.config.json' }
  notify:
      - restart neo

- name: Deploy sysctl config
  template: src=sysctl.d/neo.conf dest=/etc/sysctl.d/neo.conf
  notify:
      - sysctl-system

- name: Deploy startup files
  template: src={{ item.src }} dest={{ item.dest }} mode=0755
  loop:
      - { src: 'setupnmc.sh.j2', dest: '/etc/neo/setupnmc.sh' }
      - { src: 'runneo.sh.j2', dest: '/etc/neo/runneo.sh' }
  notify:
      - restart neo

- name: Deploy systemd unit file
  template: src=neo.service.j2 dest=/etc/systemd/system/neo.service
  notify:
      - restart neo

- name: Start neo service
  systemd:
      name: neo
      state: started
      enabled: yes
      daemon_reload: yes
