- name: restart neo-nss
  systemd:
      name: neo-nss
      state: restarted
      daemon_reload: yes

- name: unzip v2ray
  listen: deploy v2ray
  unarchive:
      src: /opt/neo/v2ray.zip
      dest: /opt/neo/v2ray/
      remote_src: yes

- name: Ensure v2ray binaries executable bit set
  listen: deploy v2ray
  file: path={{ item }} mode=0755
  loop:
      - /opt/neo/v2ray/v2ray
      - /opt/neo/v2ray/v2ctl

- name: restart neo-v2ray
  systemd:
      name: neo-v2ray
      state: restarted
      daemon_reload: yes

- name: restart neo interfaces - ifdown force
  listen: restart neo interfaces
  command: ifdown --force -v neo-macvlan-{{ item }}
  loop: "{{ range(1, 7+1)|list }}"

- name: restart neo interfaces - ifup
  listen: restart neo interfaces
  command: ifup -v neo-macvlan-{{ item }}
  loop: "{{ range(1, 7+1)|list }}"

- name: restart neostats
  listen: restart neostats
  systemd:
      name: neo-neostats
      state: restarted
      daemon_reload: yes

- name: restart neostats timer
  listen: restart neostats timer
  systemd:
      name: neo-neostats-rotate.timer
      state: restarted
      daemon_reload: yes
