- name: restart neo-nss
  systemd:
      name: neo-nss
      state: restarted
      daemon_reload: yes

- name: restart neo-v2ray
  systemd:
      name: neo-v2ray
      state: restarted
      daemon_reload: yes

- name: restart neo interfaces - ifdown force
  listen: restart neo interfaces
  command: ifdown --force -v neo-macvlan-{{ item }}
  loop: "{{ range(1, 7+1)|list }}"

- name: restart neo interfaces - ifup
  listen: restart neo interfaces
  command: ifup -v neo-macvlan-{{ item }}
  loop: "{{ range(1, 7+1)|list }}"

- name: restart neostats
  listen: restart neostats
  systemd:
      name: neo-neostats
      state: restarted
      daemon_reload: yes

- name: restart neostats timer
  listen: restart neostats timer
  systemd:
      name: neo-neostats-rotate.timer
      state: restarted
      daemon_reload: yes
